### ISSUE TITLE
Language Problem

### ISSUE THREAD

**Issue by SarthakTools** [limafresh/Brushshe#1]
Hello brother,
I can't understand your language i can guess it is russian but i am an indian so i don't know russsssssian.

**Comment by limafresh** [comment]
This is Ukrainian. But I also know Russian. I will add multilingualism someday.

Here is a screenshot in English:

![screenshot1](https://github.com/user-attachments/assets/379d4d5b-b059-45af-9ac0-fefdc36a0b60)

**Comment by limafresh** [comment]
This is Ukrainian. But I also know Russian. I will add multilingualism someday.

**Comment by limafresh** [comment]
Hi @SarthakTools !

**The application is now internationalized!** It detects what language the system is running and applies it. Translations are JSON files that have a locale name (e.g. `ru.json`, `uk.json`).

If you want, you can help translate to Indian by creating `hi.json`, copying the existing Brushshe locale examples, and filling in the second part in Indian.

For example

```json
{
	"File": "फ़ाइल",
	"Open from file": "फ़िललेट से खोलें",
	"Export to PC": "फिर पीसी निर्यात करें",
	"Background": "पृष्ठभूमि"
}
```
By agreeing to translate, you agree that the translation will be under the [CC0](https://creativecommons.org/publicdomain/zero/1.0/) license.

![screenshot1](https://github.com/user-attachments/assets/d347a900-376d-4c6a-90dc-d11cb9fb4c98)

How do you like my completed work?

**Comment by SarthakTools** [comment]
Ok brother

**Comment by SarthakTools** [comment]
> Hi @SarthakTools !
> 
> **The application is now internationalized!** It detects what language the system is running and applies it. Translations are JSON files that have a locale name (e.g. `ru.json`, `uk.json`).
> 
> If you want, you can help translate to Indian by creating `hi.json`, copying the existing Brushshe locale examples, and filling in the second part in Indian.
> 
> For example
> 
> ```json
> {
> 	"File": "फ़ाइल",
> 	"Open from file": "फ़िललेट से खोलें",
> 	"Export to PC": "फिर पीसी निर्यात करें",
> 	"Background": "पृष्ठभूमि"
> }
> ```
> 
> By agreeing to translate, you agree that the translation will be under the [CC0](https://creativecommons.org/publicdomain/zero/1.0/) license.
> 
> ![screenshot1](https://private-user-images.githubusercontent.com/173814432/388889526-d347a900-376d-4c6a-90dc-d11cb9fb4c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjk5NTMsIm5iZiI6MTczMjM2OTY1MywicGF0aCI6Ii8xNzM4MTQ0MzIvMzg4ODg5NTI2LWQzNDdhOTAwLTM3NmQtNGM2YS05MGRjLWQxMWNiOWZiNGM5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxMzQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWUwZmJlMDk4NzRmNDQwNjc1YmEwY2I5ZWU4ZTBlMDc3MDBmOWY1NmUyNTBjNWNlMTEwZDJkYjhjYTE2YTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HR1DNEaM9YJNj4ZxLt7IYuWMBDo3BjGvXK6m6hyxmuM)
> 
> How do you like my completed work?

Your work is great I even have a youtube channel actually I am struck in studies now so I can't code I am just 16 years old in class 11 I love coding I have many projects made and and a great vision of incredible projects but currently I can't make them but I try my best if you want I can provide you projects brother...😊😊😊😊😊
